apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: apicurio-registry
          image: apicurio/apicurio-registry:3.0.9
          env:
            - name: APICURIO_STORAGE_KIND
              value: "sql"
            - name: APICURIO_STORAGE_SQL_KIND
              value: "postgresql"
            - name: APICURIO_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-cluster-rw.cnpg-cluster:5432/apicurio-registry"
            - name: APICURIO_DATASOURCE_USERNAME
              value: "apicurio-registry"
            - name: APICURIO_REST_MUTABILITY_ARTIFACT_VERSION_CONTENT_ENABLED
              value: "true"
            - name: APICURIO_REST_DELETION_ARTIFACT_ENABLED
              value: "true"
            - name: APICURIO_REST_DELETION_ARTIFACT_VERSION_ENABLED
              value: "true"
            - name: APICURIO_REST_DELETION_GROUP_ENABLED
              value: "true"
            - name: APICURIO_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: apicurio-registry-db
            - name: QUARKUS_OIDC_TENANT_ENABLED
              value: "true"
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: "https://apicurio-registry.${DOMAIN}/realms/hopps"
            - name: APICURIO_UI_AUTH_OIDC_REDIRECT_URI
              value: "https://apicurio-registry.${DOMAIN}"
            - name: QUARKUS_OIDC_CLIENT_ID
              value: "apicurio-registry-api"
            - name: APICURIO_UI_AUTH_OIDC_CLIENT_ID
              value: "apicurio-registry-ui"
            - name: QUARKUS_OIDC_TLS_VERIFICATION
              value: "true"
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault