apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dtrack
  namespace: dtrack
spec:
  chart:
    spec:
      chart: dependency-track
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: dtrack
        namespace: flux-system
      version: 0.21.0
  interval: 1m0s
  values:
    ingress:
      enabled: true
      hostname: dtrack.${DOMAIN}
      ingressClassName: nginx
      tls:
        - hosts:
          - dtrack.${DOMAIN}
          secretName: dtrack-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    frontend:
      extraEnv:
        - name: "OIDC_CLIENT_ID"
          value: dtrack
        - name: "OIDC_ISSUER"
          value: https://auth.${DOMAIN}/realms/hopps
    apiServer:
      persistentVolume:
        className: "longhorn"
        enabled: true
      extraEnv:
        - name: "ALPINE_DATABASE_MODE"
          value: external
        - name: "ALPINE_DATABASE_URL"
          value: jdbc:postgresql://postgres-cluster.postgres-cluster:5432/dtrack
        - name: "ALPINE_DATABASE_DRIVER"
          value: org.postgresql.Driver
        - name: "ALPINE_DATABASE_USERNAME"
          valueFrom:
            secretKeyRef:
              key: username
              name: dtrack.dtrack.postgres-cluster.credentials.postgresql.acid.zalan.do
        - name: "ALPINE_DATABASE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: password
              name: dtrack.dtrack.postgres-cluster.credentials.postgresql.acid.zalan.do
        # oidc
        - name: "ALPINE_OIDC_ENABLED"
          value: 'true'
        - name: "ALPINE_OIDC_CLIENT_ID"
          value: dtrack
        - name: "ALPINE_OIDC_ISSUER"
          value: https://auth.${DOMAIN}/realms/hopps
        - name: "ALPINE_OIDC_USERNAME_CLAIM"
          value: preferred_username
        - name: "ALPINE_OIDC_USER_PROVISIONING"
          value: 'true'
        - name: "ALPINE_OIDC_TEAMS_CLAIM"
          value: groups
        - name: "ALPINE_OIDC_TEAMS_SYNCHRONIZATION"
          value: 'true'
        - name: "ALPINE_OIDC_USERNAME_CLAIM"
          value: preferred_username
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: dtrack-dependency-track-cloud
  namespace: dtrack
spec:
  ingressClassName: nginx
  rules:
    - host: dtrack.${DOMAIN_2}
      http:
        paths:
          - backend:
              service:
                name: dtrack-dependency-track-api-server
                port:
                  name: web
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: dtrack-dependency-track-api-server
                port:
                  name: web
            path: /health
            pathType: Prefix
          - backend:
              service:
                name: dtrack-dependency-track-frontend
                port:
                  name: web
            path: /
            pathType: Prefix
    - host: dtrack.${DOMAIN_3}
      http:
        paths:
          - backend:
              service:
                name: dtrack-dependency-track-api-server
                port:
                  name: web
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: dtrack-dependency-track-api-server
                port:
                  name: web
            path: /health
            pathType: Prefix
          - backend:
              service:
                name: dtrack-dependency-track-frontend
                port:
                  name: web
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - dtrack.${DOMAIN_2}
      secretName: dtrack-app-tls
    - hosts:
        - dtrack.${DOMAIN_3}
      secretName: dtrack-cloud-tls
