apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  chart:
    spec:
      chart: oauth2-proxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      version: 10.4.3
  interval: 1m0s
  values:
    config:
      cookieName: "oauth2-proxy"
      existingConfig: oauth2-proxy
      # kics-scan ignore-line
      existingSecret: oauth2-proxy
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 300Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - ${OAUTH_PROXY_DOMAIN}
      tls:
        - secretName: oauth2-proxy-tls
          hosts:
            - ${OAUTH_PROXY_DOMAIN}
    sessionStorage:
      type: redis
      redis:
        existingSecret: oauth2-proxy-redis
    # Sub-Chart configuration
    redis-ha:
      enabled: true
      replicas: 1
      redis:
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        # configure when only one redis server is running
        config:
          min-replicas-to-write: 0
      # disable networkPolicy as CiliumNetworkPolicy is used
      networkPolicy:
         enabled: false
      auth: true
      existingSecret: oauth2-proxy-redis
      authKey: redis-password
      # enable exporter
      exporter:
        enabled: true
        # enable scraping from prometheus
        serviceMonitor:
          enabled: true
      # add alerts for redis
      prometheusRule:
        enabled: true
        rules:
          - alert: RedisPodDown
            expr: |
              redis_up{job="{{ include "redis-ha.fullname" . }}"} == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              description: Redis pod {{ "{{ $labels.pod }}" }} is down
              summary: Redis pod {{ "{{ $labels.pod }}" }} is down
      # configure storage
      persistentVolume:
        size: 1Gi
