# default deny all except DNS
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
spec:
  description: "Block all the traffic (except DNS) by default"
  ingress:
    - {}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: UDP
          rules:
            dns:
              - matchPattern: '*'
  endpointSelector:
    matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: NotIn
        values:
          - kube-system
---
# allow ingress from ingress-nginx
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: ingress-nginx
            io.kubernetes.pod.namespace: ingress-nginx
      toPorts:
        - ports:
            - port: "4180"
---
# allow ingress from prometheus
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-from-prometheus
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: kube-prometheus-stack-prometheus
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "44180"
---
# allow ingress from oauth2-proxy to redis-master
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-to-redis-master-from-oauth2-proxy
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-master
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: oauth2-proxy
            io.kubernetes.pod.namespace: oauth2-proxy
      toPorts:
        - ports:
            - port: "6379"
---
# allow ingress from redis-replica to redis-master
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-to-redis-master-from-redis-replica
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-master
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-replica
      toPorts:
        - ports:
            - port: "6379"
---
# allow ingress from redis-master to redis-replica
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-to-redis-replica-from-redis-master
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-replica
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-master
            io.kubernetes.pod.namespace: oauth2-proxy
      toPorts:
        - ports:
            - port: "6379"
---
# allow egress from oauth2-proxy to redis-master
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-to-redis
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy
  egress:
    - toEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-master
            io.kubernetes.pod.namespace: oauth2-proxy
      toPorts:
        - ports:
            - port: "6379"
---
# allow egress from redis-master to redis-replica
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-from-redis-master-to-redis-replica
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-master
  egress:
    - toEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-replica
            io.kubernetes.pod.namespace: oauth2-proxy
      toPorts:
        - ports:
            - port: "6379"
---
# allow egress from redis-replica to redis-master
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-from-redis-replica-to-redis-master
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-replica
  egress:
    - toEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: oauth2-proxy-redis-master
      toPorts:
        - ports:
            - port: "6379"
---
# allow egress traffik from oauth2-proxy to keycloak
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-to-keycloak
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy
  egress:
    - toFQDNs:
        - matchPattern: "*.${DOMAIN}"
        - matchPattern: "*.${DOMAIN_2}"
        - matchPattern: "*.${DOMAIN_3}"
      toPorts:
        - ports:
            - port: "443"
---
# allow egress for keycloak callback
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-to-keycloak-callback
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: oauth2-proxy
  egress:
    - toEntities:
        - "world"
        - "cluster"
---
# allow ingress for acme TLS
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-acme-solver
spec:
  endpointSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.serviceaccount: ingress-nginx
            io.kubernetes.pod.namespace: ingress-nginx
      toPorts:
        - ports:
            - port: "8089"
