# configs
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configs
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/captain-kube/configs
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# prometheus-operator-crds
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/captain-kube/prometheus-operator-crds
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: prometheus-operator-crds
      namespace: flux-system
---
# cert-manager
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/cert-manager
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
---
# longhorn
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/longhorn
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# cilium
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: cert-manager
  path: ./infrastructure/captain-kube/cilium
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: kube-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# cluster-issuer
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
  path: ./infrastructure/captain-kube/cluster-issuer
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# ingress-nginx
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/ingress-nginx
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
---
# minio
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: longhorn
  path: ./infrastructure/captain-kube/minio
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: minio
      namespace: minio
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# postgres-operator
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/postgres-operator
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: postgres-operator
      namespace: postgres-operator
---
# postgres-operator-ui
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator-ui
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: postgres-operator
  path: ./infrastructure/captain-kube/postgres-operator-ui
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: postgres-operator-ui
      namespace: postgres-operator-ui
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# postgres-cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-cluster
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: postgres-operator
  path: ./infrastructure/captain-kube/postgres-cluster
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# keycloak
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: postgres-cluster
  path: ./infrastructure/captain-kube/keycloak
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: keycloak
      namespace: keycloak
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# vaultwarden
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: postgres-cluster
    - name: longhorn
  path: ./infrastructure/captain-kube/vaultwarden
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: vaultwarden
      namespace: vaultwarden
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# kimai
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kimai
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: longhorn
  path: ./infrastructure/captain-kube/kimai
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kimai
      namespace: kimai
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# mariadb-operator
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: cert-manager
  path: ./infrastructure/captain-kube/mariadb-operator
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: mariadb-operator
      namespace: mariadb-operator
---
# mariadb
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: minio
    - name: mariadb-operator
  path: ./infrastructure/captain-kube/mariadb
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# dtrack
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dtrack
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: postgres-cluster
    - name: cert-manager
  path: ./infrastructure/captain-kube/dtrack
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: dtrack
      namespace: dtrack
---
# kube-prometheus-stack
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: longhorn
  path: ./infrastructure/captain-kube/kube-prometheus-stack
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: loki-stack
      namespace: monitoring
---
# oauth2-proxy
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: longhorn
    - name: configs
  path: ./infrastructure/captain-kube/oauth2-proxy
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: oauth2-proxy
      namespace: oauth2-proxy
---
# metrics-server
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/metrics-server
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metrics-server
      namespace: metrics-server
---
# kubernetes-dashboard
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: oauth2-proxy
  path: ./infrastructure/captain-kube/kubernetes-dashboard
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kubernetes-dashboard
      namespace: kubernetes-dashboard
---
# cloudnative-pg-operator
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: prometheus-operator-crds
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/captain-kube/cloudnative-pg
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cloudnative-pg
      namespace: cnpg-system
---
# cloudnative-pg-cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: prometheus-operator-crds
    - name: cloudnative-pg-operator
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/captain-kube/cloudnative-pg-cluster
  prune: true
  #healthChecks:
  #  - apiVersion: helm.toolkit.fluxcd.io/v2
  #    kind: HelmRelease
  #    name: postgres-cluster
  #    namespace: cnpg-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# apicurio-studio
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apicurio-studio
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: cloudnative-pg-cluster
  path: ./infrastructure/captain-kube/apicurio-studio
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: apicurio-studio
      namespace: apicurio-studio
---
# apicurio-registry
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apicurio-registry
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: cloudnative-pg-cluster
  path: ./infrastructure/captain-kube/apicurio-registry
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
#  healthChecks:
#    - apiVersion: helm.toolkit.fluxcd.io/v2
#      kind: HelmRelease
#      name: apicurio-studio
#      namespace: apicurio-studio
---
# minecraft
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn
  path: ./infrastructure/captain-kube/minecraft
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: minecraft
      namespace: minecraft
---
# fest-der-demokratie
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fest-der-demokratie
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx
    - name: cert-manager
  path: ./infrastructure/captain-kube/fest-der-demokratie
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: fest-der-demokratie
      namespace: fest-der-demokratie
---
# juno-care
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: juno-care
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn
    - name: ingress-nginx
    - name: cert-manager
  path: ./infrastructure/captain-kube/juno-care
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: juno-care
      namespace: juno-care
