# configs
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configs
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/captain-kube/configs
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# prometheus-operator-crds
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/captain-kube/prometheus-operator-crds
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: prometheus-operator-crds
      namespace: flux-system
---
# cert-manager
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/cert-manager
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
---
# longhorn
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/longhorn
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# cilium
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: cert-manager
  path: ./infrastructure/captain-kube/cilium
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: kube-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# cluster-issuer
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
  path: ./infrastructure/captain-kube/cluster-issuer
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# ingress-nginx
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/ingress-nginx
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
---
# minio
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: longhorn
  path: ./infrastructure/captain-kube/minio
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: minio
      namespace: minio
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# postgres-operator
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/postgres-operator
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: postgres-operator
      namespace: postgres-operator
---
# postgres-operator-ui
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator-ui
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: postgres-operator
  path: ./infrastructure/captain-kube/postgres-operator-ui
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: postgres-operator-ui
      namespace: postgres-operator-ui
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# postgres-cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-cluster
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: postgres-operator
  path: ./infrastructure/captain-kube/postgres-cluster
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: postgres-cluster
      namespace: postgres-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
