# configs
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configs
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/captain-kube/configs
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# prometheus-operator-crds
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/captain-kube/prometheus-operator-crds
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: prometheus-operator-crds
      namespace: flux-system
---
# cert-manager
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/cert-manager
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
---
# longhorn
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
  path: ./infrastructure/captain-kube/longhorn
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
---
# cilium
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: prometheus-operator-crds
    - name: cert-manager
  path: ./infrastructure/captain-kube/longhorn
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: kube-system
