apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup-digital-ocean
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb-galera
  schedule:
    cron: "*/1 * * * *"
    suspend: false
  maxRetention: 720h # 30 days
  storage:
    s3:
      bucket: mariadb-operator
      endpoint: digitaloceanspaces.com
      region: fra1
      prefix: hopps
      accessKeyIdSecretKeyRef:
        name: mariadb-secret
        key: digital-ocean-access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb-secret
        key: digital-ocean-secret-access-key
      tls:
        enabled: true
