apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juno-care-data
  namespace: juno-care
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
