apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apps/vaultwarden
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: vaultwarden-secret
    namespace: vaultwarden
    envs:
      - secret-encrypted.env
