apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/traefik/traefik-helm-chart
  ref:
    # should match helm chart version
    tag: v41.0.2
  # only add traefik crds
  ignore: |
    # exclude
    /*
    # include
    !traefik/crds
