apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: juno-care
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:BdmmKI5z8qg0bQYHWlZCKzefZaZQI1LmznV4C/4Y1fSgujBfjW3gJJ3GNBOt50JyvlT0z5hl1JMKImfZKxIdfZ5dvuxeKjyRjYLYs2PZ9HVBY5ONL1Onv0z30CTtzTjVUYVE0B2dQRpQi+KvlFr9DZmOcLYrulvigg2/E9INYOtLAR+zW3cq9fUjZg==,iv:Mhll9gU9M7hTfSNrN6CMWogAB0vo/n1ROuQ1bsYFZ1c=,tag:wHYNMGPIVcVu/SqDmW9lDw==,type:str]
sops:
    age:
        - recipient: age1ffsgx4kzutechq3p20sxxc8x4p2zg8xvwmzj6dhercecec543dtsdq27ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWmtubHdmYkdxRG5xRjkw
            bXh1SVFoOTZDcHB5NWY1L1pROXVsaWtkRTE0CnA2L0dXc2ttSmdDeEh5eWtxM1BQ
            TkN2ZzdZSFBsMm5KbFoyaktWeXl5bGsKLS0tIHd1c2ZXQk8xSUtZQjZzZUphcGMv
            WHZ3YXN0ZTFZMmJBWWYra1BuR3FqWVkKnh8+Xzl8Fuad0pbzvIiMzY/5q0BD+pSM
            FMN194367UeOgraKaesU7SWT9EEeEGsdqDotNZMf6GygLtx9cxL82w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T18:54:21Z"
    mac: ENC[AES256_GCM,data:FzXTvoiTZbg0+6gLl6oxMz4rnNHXcTGhZ91Bz5i8Lz8FK6jOE9aFbEjubYbsQSITbQT3rgKPgDoi1mZ4HcGUsbvmOYA7DRIVheP3Rb7VzMIsiLdfdriW7xCTjYSllChSSZIIsXLhtP20fc0BZ6qn+aiNe8Yi8UW5KzM113L31Zw=,iv:MgwgnDPwCaqRUvAgswGSy9AlQk2ibnhIqIhwxDpceYM=,tag:N1nY1igYXfKapJOx9MP5Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
