apiVersion: v1
kind: Secret
metadata:
    name: juno-secret-key
    namespace: juno-care
stringData:
    JUNO_SECRET_KEY: ENC[AES256_GCM,data:/ltaO/HLWkx068dIwGDV0QpfBssaEueJp0jfR2JDOyQ5n8zhiAUwVlBH1P+Z2Sy9rFPv7w12vef60MJv29nXKw==,iv:y8QvWQ+ohroXva4jyZjLRu0dlNXkUayHk8Zfq5f3kVQ=,tag:VpSkrCcshdfbRNNmdHZiqg==,type:str]
sops:
    age:
        - recipient: age1ffsgx4kzutechq3p20sxxc8x4p2zg8xvwmzj6dhercecec543dtsdq27ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaDh4bjZVNHNHZk1XWEgv
            OTloZkpGM0tyRHEyMnlzajlwLzl5YzZGV0FVCnMrM3RBY3hvTmU5eUNhL0MxanRV
            R0RyVmc1ZnJFRk4yTENZdVdFU2VvZkEKLS0tIExweUJzemY1YXNKQlNWUVIvelJC
            Y05DbTVsaEFtN0NZZFd1TEo3Um9WNkUKJratih0oSPJQ/+hndj37a6Hr/CNkU8tj
            r5dCMTXa28pn9wybVeIlFnB7Aej9d84UoU5FHTHFJ96MNbVe2AQv8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T19:00:40Z"
    mac: ENC[AES256_GCM,data:Df6a1aBpl29wV/f2/l1iHIKlwzXdHFRYzdjgfGn2lKCt1/agZ7SZ3U4L6w3NGw41m5EfiolCcewwxDS3TyIjD7RSAFF/gKIWVgNF5FSmruP5d8ievBe+tzyBu3ZdyfjokscBDCsKs+StjWJ2rxMSfMWLKnCL2Nw5qhxH2tAgj2I=,iv:4Df/xuDAQOeVHLo8JaUU2p/zCQhjDRrWcBFLyMy8QgQ=,tag:EmwL+1/HT77ka7Hk0R0dBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
