apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apps/kimai
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: kimai-secret
    namespace: kimai
    envs:
      - secret-encrypted.env
